### ISSUE TITLE
libuv version?

### ISSUE THREAD

**Issue by jvirtanen** [penberg/helix#1]
Which version of libuv does Helix require? I have libuv 1.6.1 and its API is incompatible with the API Helix uses.

**Comment by penberg** [comment]
I'm building against 0.10.34 which is shipped in Fedora 21. I think we should move to a newer release, though.

**Comment by ghost** [comment]
@penberg @jvirtanen i think that `libuv` or whatever event library do not add really much value in this type of workload vs just a simple `poll(2)`. these libs trying to do their own locking, often use `pthread`, etc

**Comment by ghost** [comment]
@penberg disregard, actually you don't do networking, sorry

**Comment by penberg** [comment]
@divaykin Yes, so `libuv` is only used by the tools and example code. The core code just expects packets to arrive from somewhere.

**Comment by ghost** [comment]
yeah 1.0 would be great

**Comment by penberg** [comment]
I'll fix it up.
