### ISSUE TITLE
tool - resample ITCH to BBO file

### ISSUE THREAD

**Issue by ghost** [penberg/helix#5]
one of my most important applications to decent ITCH parser would be resampling data files into BBO (only best bid price, total size, # of orders, best ask, total size, # of orders) format. plus trades.

the output format would be simple fixed offsets with timestamp, current bid & ask, order book id in case of new quote. and timestamp, price, aggressor, size of a trade.

**Comment by penberg** [comment]
`helix-trace` works directly on files so you can use that for this. There's even a Python script to plot the sample data.

**Comment by ghost** [comment]
thanks

**Comment by ghost** [comment]
but `helix-trace` reads the data from network, would be great to be able to read ITCH from files instead of multicast groups. there is no need to do `tcpreplay` or alike

**Comment by penberg** [comment]
@divaykin Aah, right, I only implemented it for `helix-svm` in commit d3c06055b35fd730fb15e88fc160126b6c627b49. The capability is there, we just need to make `helix-trace` use it.

**Comment by jvirtanen** [comment]
@divaykin Take a look at [NASDAQ Market Data Tools](https://github.com/jvirtanen/nasdaq-tools) as well.

**Comment by ghost** [comment]
thanks @jvirtanen will do
